// <auto-generated />
namespace WAD.WebApp._10888.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SteakCategoryModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SteakCategoryModels));
        
        string IMigrationMetadata.Id
        {
            get { return "202104200900224_SteakCategoryModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
